# Docker-Compose configuration file.

# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  starter-mysql-data:
    driver: local

  # Redis Data
  starter-redis-data:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: starter-api-mysql
    volumes:
      - starter-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=starter
      - MYSQL_DATABASE=starter
      - MYSQL_USER=starter
      - MYSQL_PASSWORD=starter

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: starter-api-redis
    command: --appendonly yes
    volumes:
      - starter-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy) - Web Application (API)
  web:
    image: ambientum/php:7.0-caddy
    container_name: starter-api-web
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    links:
      - mysql
      - cache

  # Queues
  queue:
    image: ambientum/php:7.0
    container_name: starter-api-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache